"""Rich terminal, JSON, and Markdown output formatters for rulegraph."""

from __future__ import annotations

import json
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from rulegraph.rule import ArbitrationResult, RuleNode

_console = Console()


def _truncate(text: str, max_len: int = 72) -> str:
    """Truncate text to max_len characters, appending ellipsis if needed."""
    return text if len(text) <= max_len else text[: max_len - 1] + "…"


def print_result(result: ArbitrationResult, console: Console | None = None) -> None:
    """Print a single ArbitrationResult to the terminal using Rich.

    Args:
        result: The ArbitrationResult to display.
        console: Optional Rich Console to write to (defaults to stdout).
    """
    con = console or _console

    tier_colour = {
        "determinate": "green",
        "indeterminate": "yellow",
        "unknown": "dim",
    }.get(result.tier, "white")

    con.print(
        Panel(
            f"[bold]Query:[/bold] {result.query}\n"
            f"[bold]Tier:[/bold] [{tier_colour}]{result.tier}[/{tier_colour}]  "
            f"[bold]Confidence:[/bold] {result.confidence:.0%}",
            expand=False,
            border_style=tier_colour,
        )
    )
    con.print(f"[dim]{result.answer}[/dim]")

    if result.provenance:
        con.print(
            f"\n[dim]Provenance ({len(result.provenance)}): "
            + ", ".join(result.provenance[:5])
            + (" …" if len(result.provenance) > 5 else "")
            + "[/dim]"
        )

    if result.contradictions:
        con.print("[bold red]Contradictions:[/bold red] " + ", ".join(result.contradictions))
    con.print()


def print_rules(rules: list[RuleNode], console: Console | None = None) -> None:
    """Print a list of RuleNode objects in a compact table.

    Args:
        rules: The rules to display.
        console: Optional Rich Console to write to (defaults to stdout).
    """
    con = console or _console

    if not rules:
        con.print("[dim]No rules found.[/dim]")
        return

    table = Table(show_header=True, header_style="bold", box=None, padding=(0, 1))
    table.add_column("ID", width=16)
    table.add_column("Rule ID", width=24)
    table.add_column("Type", width=12)
    table.add_column("Tags", width=20)
    table.add_column("Text (excerpt)", no_wrap=False)

    for rule in rules:
        tags_str = ", ".join(rule.tags[:3])
        if len(rule.tags) > 3:
            tags_str += f" +{len(rule.tags) - 3}"
        table.add_row(
            Text(rule.id, style="dim"),
            rule.rule_id,
            rule.node_type,
            tags_str,
            _truncate(rule.text, 60),
        )

    con.print(table)
    con.print()


def to_json(
    rules: list[RuleNode] | None = None,
    result: ArbitrationResult | None = None,
) -> str:
    """Serialize rules and/or an arbitration result to JSON.

    Args:
        rules: Optional list of RuleNode objects to include.
        result: Optional ArbitrationResult to include.

    Returns:
        A JSON string suitable for programmatic consumption.
    """
    data: dict[str, Any] = {}
    if rules is not None:
        data["rules"] = [r.to_dict() for r in rules]
        data["rule_count"] = len(rules)
    if result is not None:
        data["result"] = result.to_dict()
    return json.dumps(data, indent=2)


def to_markdown(results: list[ArbitrationResult]) -> str:
    """Generate a Markdown report from a list of ArbitrationResult objects.

    Args:
        results: List of ArbitrationResult objects.

    Returns:
        A Markdown string suitable for display in GitHub PRs or documentation.
    """
    if not results:
        return "## rulegraph arbitration report\n\nNo results to display.\n"

    lines = [
        "## rulegraph arbitration report",
        "",
        f"**{len(results)} query result(s)**",
        "",
        "| Tier | Confidence | Query | Contradictions |",
        "|------|-----------|-------|----------------|",
    ]

    for r in results:
        tier = r.tier
        conf = f"{r.confidence:.0%}"
        query = _truncate(r.query.replace("|", "\\|"), 50)
        contras = str(len(r.contradictions)) if r.contradictions else "—"
        lines.append(f"| {tier} | {conf} | {query} | {contras} |")

    lines += [
        "",
        "<details><summary>Full JSON</summary>",
        "",
        "```json",
        json.dumps([r.to_dict() for r in results], indent=2),
        "```",
        "",
        "</details>",
        "",
        "*Generated by [rulegraph](https://github.com/sandeep-alluru/rulegraph)*",
    ]
    return "\n".join(lines)
